import numpy as np

class OrbConfig:
    max_features: int
    fast_cells: int
    deep_cells: int
    max_hamming_distance: int
    confidence_threshold: float
    resize_dim: int
    def __init__(self) -> None: ...

class MatchResult:
    label: str
    confidence: float
    fallback_used: bool

class Vault:
    def __init__(self, config: OrbConfig) -> None: ...
    def add(self, image: np.ndarray, label: str) -> None: ...
    def add_batch(self, images: list, labels: list) -> None: ...
    def build(self) -> None: ...
    def search(self, image: np.ndarray) -> MatchResult: ...
    def stats(self) -> dict: ...
    def save(self, prefix: str) -> None: ...
    def load(self, prefix: str) -> None: ...
